name: test main

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always
  SUITESPARSE_GRAPHBLAS_SYS_COMPILER_PATH: /usr/lib/gcc/x86_64-linux-gnu/11/
  SUITESPARSE_GRAPHBLAS_SYS_OPENMP_STATIC_LIBRARY_NAME: gomp

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
